version: "3"
services:
  app:
    build: .
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - db
  db:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - ./mysql-data:/var/lib/mysql
