version: "3"
services:
  app:
    build:
      context: ../..
      target: app
    tty: true
    volumes:
      - .:/usr/src/main/packages/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/mydb
    command: npm start -w packages/app
    depends_on:
      - db
  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    # volumes:
    #   - ./mysql-data:/var/lib/mysql
