name: Deployment
on:
  workflow_dispatch:
  push:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install
        run: npm ci
        working-directory: slide

      - name: Build
        run: npm run build -- --base=/slide-devio-2022
        working-directory: slide

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./slide/dist
